//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alteracao_Fatura
    {
        public string id_fatura { get; set; }
        public string estado_anterior { get; set; }
        public string estado_atual { get; set; }
        public System.DateTime dt_alteracao { get; set; }
    
        public virtual Fatura Fatura { get; set; }
    }
}
