//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class code
    {
        public long codigo { get; set; }
        public System.DateTime dt_criacao { get; set; }
        public bool fat { get; set; }
        public string id { get; set; }
    }
}
