//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fatura()
        {
            this.Alteracao_Fatura = new HashSet<Alteracao_Fatura>();
            this.Nota_Credito = new HashSet<Nota_Credito>();
            this.Items = new HashSet<Item>();
        }
    
        public string id { get; set; }
        public Nullable<long> nif { get; set; }
        public Nullable<System.DateTime> dt_emissao { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> valor_total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alteracao_Fatura> Alteracao_Fatura { get; set; }
        public virtual Contribuinte Contribuinte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota_Credito> Nota_Credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
