//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatura_contribuinte
    {
        public string id { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public string estado { get; set; }
        public long nif { get; set; }
        public string nome { get; set; }
        public string morada { get; set; }
    }
}
